# Perguntas
1. Rafaça o código de treinamento da aula 12: “K-Nearest Neighbors - Prática”  no seu computador usando o Jupyter Notebook ou o Google Colabs.
2. Retreino o algoritmo com os seguintes valores para K: [3, 5, 7, 9, 11, 13, 15, 17, 19 e 21] e anote a acurácia.
3. Qual o problema principal de usar a métrica acurácia? Escreve um exemplo hipotético, no qual o problema acontece.
4. Explique com um pequeno texto ilustrando a diferença entre a métrica de Precision e Recall e mostrando quando usa deve ser escolhida em relação a outra
5. Escreve um trecho de código que automatize o treinamento do algoritmo KNN, a fim de encontrar o melhor valor para K, do exercício 2.
6. Escreva um pequeno texto, explicando as 6 denominações da matriz de confusão: P, N, TP, FN, FP e TN
7. No conjunto de dados usado na aula 12: “K-Nearest Neighbors - Prática”, existe alguma variável que fere as premissas do K-NN? Se sim ou não, explique.

#### Instalando as bibliotecas necessárias

In [12]:
#%pip install pandas
#%pip install -U scikit-learn
#%pip install seaborn

#### 1. Rafaça o código de treinamento da aula 12: “K-Nearest Neighbors - Prática”  no seu computador usando o Jupyter Notebook ou o Google Colabs.

In [21]:
# Importando as bibliotecas necessárias

import pandas as pd 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [14]:
# Importando os dados

path = "/home/bruno/repos/Fundamentos_ML/data/train.csv"
df = pd.read_csv(path, low_memory=False)
df.head()

,id_cliente,idade,saldo_atual,divida_atual,renda_anual,valor_em_investimentos,taxa_utilizacao_credito,num_emprestimos,num_contas_bancarias,num_cartoes_credito,dias_atraso_dt_venc,num_pgtos_atrasados,num_consultas_credito,taxa_juros,investe_exterior,pessoa_polit_exp,limite_adicional
0,1767,21,278.172008,2577.05,24196.89636,104.306544,31.038763,6,5,7,21,14,9,15,Não,Não,Negar
1,11920,40,268.874152,2465.39,19227.37796,69.858778,36.917093,5,8,5,40,23,10,18,Não,Não,Negar
2,8910,36,446.643127,1055.29,42822.28223,134.201478,34.561714,0,3,6,26,13,3,15,Sim,Não,Negar
3,4964,58,321.141267,703.05,51786.82600,297.350067,31.493561,0,3,7,12,7,2,1,Sim,Não,Negar
4,10100,35,428.716114,891.29,44626.85346,134.201478,28.028887,2,8,7,24,10,8,20,Sim,Não,Negar

In [15]:
# Selecionando as variáveis para o KNN
# Apenas variáveis que podem ser descritas em termos da distância entre dois elementos

features = ['idade', 'saldo_atual', 'divida_atual', 'renda_anual', 'valor_em_investimentos',  
            'taxa_utilizacao_credito', 'num_emprestimos', 'num_contas_bancarias', 'num_cartoes_credito',  
            'dias_atraso_dt_venc', 'num_pgtos_atrasados', 'num_consultas_credito', 'taxa_juros']


label = ['limite_adicional']

In [16]:
# Preparação dos dados de treinamento

x_train = df.loc[:, features] 
y_train = df.loc[:, label].values.ravel()

In [17]:
# Treinamento do algoritmo KNN 

knn_classifier = KNeighborsClassifier( n_neighbors = 8 ) 
knn_classifier.fit( x_train, y_train )

KNeighborsClassifier(n_neighbors=8)

In [18]:
# Previsão das observações 

y_pred = knn_classifier.predict( x_train )

In [19]:
# Comparação do Previsto com o Realizado 

df1 = df.loc[:, ['id_cliente', 'limite_adicional']] 
df1['predicted'] = y_pred

In [20]:
df1.sample(20).reset_index()

    index  id_cliente limite_adicional predicted
0    2721        2981         Conceder     Negar
1    4819        4552         Conceder     Negar
2    6879        5975            Negar     Negar
3    4786        4699            Negar     Negar
4    1006        2448            Negar     Negar
5    1338       11283            Negar     Negar
6    6503       10900            Negar     Negar
7    3061        6504         Conceder     Negar
8    6690        7656            Negar     Negar
9    1802        4961            Negar     Negar
10   2058        3659            Negar     Negar
11   8744        3451            Negar     Negar
12   5560        4310            Negar     Negar
13    221        1594            Negar     Negar
14    105        9211            Negar     Negar
15   5787        9041            Negar     Negar
16   4657       10574         Conceder     Negar
17   7544        3933            Negar     Negar
18   3380        3818            Negar     Negar
19   5707        4825            Negar     Negar

#### 2. Retreino o algoritmo com os seguintes valores para K: [3, 5, 7, 9, 11, 13, 15, 17, 19 e 21] e anote a acurácia.

In [24]:
accuracy_score(y_train, y_pred).round(3)

0.855

In [94]:
k_values = [3, 5, 7, 9, 11, 13, 15, 17, 19, 21]
k_values = [int(val) for val in k_values]
accuracy_values = []

for k in k_values:
    knn_classifier = KNeighborsClassifier( n_neighbors = k ) 
    knn_classifier.fit( x_train, y_train )
    
    y_pred = knn_classifier.predict( x_train )
    
    df1 = df.loc[:, ['id_cliente', 'limite_adicional']] 
    df1['predicted'] = y_pred
    
    val = accuracy_score(y_train, y_pred)
    
    accuracy_values.append(val)
    
df_aux = pd.DataFrame(data=[k_values, accuracy_values]).T
df_aux.columns = ['k_values', 'accuracy_values']

In [95]:
print(f'Os valores de acurácia para os valores de K são: \n {df_aux}')

Os valores de acurácia para os valores de K são:
    k_values  accuracy_values
0       3.0         0.885474
1       5.0         0.866737
2       7.0         0.859053
3       9.0         0.852842
4      11.0         0.850000
5      13.0         0.849263
6      15.0         0.848000
7      17.0         0.847895
8      19.0         0.847895
9      21.0         0.846211

#### 3. Qual o problema principal de usar a métrica acurácia? Escreve um exemplo hipotético, no qual o problema acontece.

> A acurácia é uma métrica que estima q quantidade de vezes que o modelo acertou uma previsão, independente da classe daquela previsão. Portanto, em casos de conjuntos de dados desbalanceados (em que uma das classes está muito mais bem representada do que a outra), o modelo pode errar a maioria das classificações pra classe rara e ainda assim obter um alto valor de acurácia, caso acerte muitas classificações da classe majoritária.

#### 4. Explique com um pequeno texto ilustrando a diferença entre a métrica de Precision e Recall e mostrando quando usa deve ser escolhida em relação a outra

> A precisão se refere ao número de vezes que o modelo classificou corretamente uma determinada classe. O retorno indica o número de vezes que o modelo conseguiu identificar corretamente a classe quando confrantado com ela. Isto é, a precisão indica a quantidade de vezes que o modelo disse que um elemento pertencia a certa classe e ele realmente pertencia a ela. O retorno indica, dado um número de elementos de uma classe no conjunto de dados, a quantidade de vezes que o modelo conseguiu identificar aquela classe corretamente.

#### 5. Escreve um trecho de código que automatize o treinamento do algoritmo KNN, a fim de encontrar o melhor valor para K, do exercício 2.

In [97]:
df_aux.sort_values(by='accuracy_values', ascending=False)

   k_values  accuracy_values
0       3.0         0.885474
1       5.0         0.866737
2       7.0         0.859053
3       9.0         0.852842
4      11.0         0.850000
5      13.0         0.849263
6      15.0         0.848000
7      17.0         0.847895
8      19.0         0.847895
9      21.0         0.846211

#### 6. Escreva um pequeno texto, explicando as 6 denominações da matriz de confusão: P, N, TP, FN, FP e TN

> P = Positivo. Vem da epidemiologia e indica os elementos pertencentes a uma certa classe
> 
> N = Negativo. Também vem da epidemio e indica os elementos pertencentes a uma classe diferentes da positiva
> 
> TP = True Positives. Indica o número de classificações positivas corretas, isto é, era Positivo e o modelo classificou como Positivo
> 
> TN = True Negatives. De modo análogo ao TP, indica o número de vezes que um elemento era Negativo e foi classificado como Negativo pelo modelo
>
> FP = False Positives. Indica o número de vezes que o modelo errou, indicando que a classe era Positiva, quando na verdade o elemento era Negativo
>
> FN = False Negatives. Indica o número de vezes que o modelo errou, indicando que a classe era Negativa, quando na verdade o elemento era Positivo
>
> FP + FN. É a soma do número de erros do modelo
>
> TP + TN. É a soma do número de acertos do modelo
>
> TP + FP. É o número de vezes que o modelo afirmou que um elemento pertencia à classe Positiva
>
> TN + FN. É o número de vezes que o modelo afirmou que um elemento pertencia à classe Negativa
>

#### 7.  conjunto de dados usado na aula 12: “K-Nearest Neighbors - Prática”, existe alguma variável que fere as premissas do KNN? Se sim ou não, explique.

> Abaixo podemos ver o cabeçalho do conjunto de dados com que estamos trabalhando e perceber que há algumas variáveis que não podem ser utilizadas para o treinamento do modelo de KNN por não serem numéricas e, portanto, não poderem servir para calcular distâncias entre elementos. São elas *id_cliente*, *investe_exterior*, *pessoa_polit_exp* e o próprio rótulo, *limite_adicional*

In [60]:
df.head(3)

,id_cliente,idade,saldo_atual,divida_atual,renda_anual,valor_em_investimentos,taxa_utilizacao_credito,num_emprestimos,num_contas_bancarias,num_cartoes_credito,dias_atraso_dt_venc,num_pgtos_atrasados,num_consultas_credito,taxa_juros,investe_exterior,pessoa_polit_exp,limite_adicional
0,1767,21,278.172008,2577.05,24196.89636,104.306544,31.038763,6,5,7,21,14,9,15,Não,Não,Negar
1,11920,40,268.874152,2465.39,19227.37796,69.858778,36.917093,5,8,5,40,23,10,18,Não,Não,Negar
2,8910,36,446.643127,1055.29,42822.28223,134.201478,34.561714,0,3,6,26,13,3,15,Sim,Não,Negar